version: "3.2"
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24
services:
  app:
    image: app
    restart: always
    build:
      context: .
      dockerfile: .dockerfiles/app.dockerfile
    volumes:
      - ".:/src"
    ports:
      - "8090:8090"
    networks:
      default:
        ipv4_address: 172.10.0.10
    depends_on:
      - redis
      - scylla-node1
  redis:
    container_name: redis-scylladb-test
    image: redis:6.2.6
    ports:
      - "6379:6379"
    networks:
      default:
        ipv4_address: 172.10.0.3
  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:4.5.0
    restart: always
    command:  --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "./scylla/mutant-data.cql:/mutant-data.cql"
#    entrypoint: sh -c "cqlsh -f /mutant-data.cql"
    networks:
      default:
        ipv4_address: 172.10.0.4
  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla:4.5.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      default:
        ipv4_address: 172.10.0.5
  scylla-node3:
    container_name: scylla-node3
    image: scylladb/scylla:4.5.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      default:
        ipv4_address: 172.10.0.6
